### ISSUE TITLE
aligning with current work at Mozilla

### ISSUE THREAD

**Issue by emmairwin** [chaoss/wg_diversity_inclusion#2]
I wanted to understand how this is coming together. 
I see influence from our shared work at Mozilla (great to see open demographics project includes) and in fact we are doing pilots right now on qualitative and quantitative community health baselines that with d&i as central. With considerations for privacy, risk, respect ,ethics and legality of measuring d&i.
How might we better align?

**Comment by germonprez** [comment]
Hi @emmairwin -- We just had our BoF (CHAOSS: Exploring Open Source Project Diversity & Inclusion) accepted at the OS Leadership Summit. Details are below. From my perspective, I'd really love to start settling on the qualitative metrics that we can use to move our understanding of D&I forward. Basically, what are the right trace components that we can look at to start crafting a better understanding of D&I. Beyond that, we are interested in the methods by which other communities could produce such reports that are relevant to their own interests.  

As an aside, I'm very interested in what you are doing qualitatively (and how you are doing it). This is my method of choice and I'd love to think through the 'how' aspects of this. 



Session Type: Birds of a Feather

Abstract: This Birds of a Feather session takes place in the context of the Linux Foundation’s CHAOSS project. The CHAOSS project’s mission is to produce integrated, open source software for analyzing software development projects, establish implementation-agnostic metrics for measuring community activity, contributions, and health; and produce standardized metric exchange formats, detailed use cases, models, or recommendations to analyze specific issues in the industry/OSS world. As open source project health and sustainability becomes an increasingly important consideration for organizations, the CHAOSS project seeks to develop the software, methods, and metrics that can help best accommodate these needs. 

In this Birds of a Feather session, Matt Germonprez and Daniel Izquierdo will focus on one particular metric supported by the CHAOSS project, Diversity & Inclusion. Matt and Daniel will discuss work that has been done to-date with respect to the open source Diversity & Inclusion reports at OpenStack, the software used to generate these reports, the relationship between these reports and the CHAOSS project, and methods by which other open source projects could generate reports of their own. 

The Birds of a Feather session will include break-out sessions for participants to discuss and report aspects of Diversity & Inclusion that are relevant within their own organization. Finally, the Birds of a Feather session will conclude with a brief discussion of the current activities in the CHAOSS project and any new initiatives that participants would like to recommend. 

Audience: The target audience for this session is community managers, project leads, steering committee members, open source project board members, or anyone interested in open source project health and sustainability.  

Benefits to the Ecosystem: This Birds of a Feather session will hone in on the practices by which open source project health and sustainability can be better understood, particularly with respect to Diversity & Inclusion. The session will advance the Linux Foundation’s CHAOSS project by being the first workshop/session that meaningfully brings together members of the CHAOSS software and metrics committees in a collaborative project. 

Experience Level: Any

**Comment by emmairwin** [comment]
Looking forward to talking more. Our processes right now starts with a base of research questions focused on identity(demographic diversity) leadership, contribution attributes (like prs) . from this base we are working with the community manager to prioritize and identify gaps.  Once our research questions are finalized we identify at all existing data sources ( surveys ,  bitergia)  which answer those. From there we can speak to ' the gaps' what don't we have - how can we obtain that knowledge? Is it simply adding a new repo to our dashboard?  Is it a survey? Or do we need to talk to interview.

At this point we define our strategy build on what we know and fill in those gaps all while answering another set of questions that keep privacy, safery and respect at center . 
The ethics of why and how  collection, visualization and access to data are critical to get right up front. And im not sure I've seen this called out in CHAOSS yet

So that's a nutshell. We have best practices and even training for qualitative research in foss. Including docs for enabling first-language interviews though volunteer training.  Ill be compiling these in the mozilla/diversity github.

**Comment by emmairwin** [comment]
Leadership summit session looks great!

**Comment by germonprez** [comment]
The ethics hasn't shown up explicitly in CHAOSS. In any interview that we do here from the university runs through our own ethics board to address the issues you bring up. Regarding the open trace data, much less so. 

Your approach is great. I like the gap/triangulation approach towards the research questions. Do you work with things like participant-observation, netnography, or action research as research frames? Sort of these long arc, deeply embedded approaches. The reason that I ask is with respect to how data is understood from internal vs. external perspectives. 

Is anyone from Mozilla heading to the Leadership Summit? I'd love a chance to have them participate in the LS session -- not to mention just meet them :)

**Comment by germonprez** [comment]
I think that we should focus on building out a roadmap

https://github.com/chaoss/wg_diversity_inclusion/pull/3

@GeorgLink started one here I think it would really help focus things.

**Comment by emmairwin** [comment]
Looks good, thank you!
